### ISSUE TITLE
Help with understanding client connection troubles

### ISSUE THREAD

**Issue by PHPGuus** [eyeson-team/react-web-gui-example#12]
Hi,

can you help me identify what happened in conference with room access key 8ExkZDVxh9ccZFp1XalOpQiq and guest token PmG7GphTuvaBgI3IVVTffLwe?

Kimberley started the conference, I (PHP Guus) joined then left, and after that a person called Adam joined. He showed up in the participant list (so was connected to eyeson), but his audio and video feed did not show up. He is using Chrome.

Thank you!
Best regards,
Guus

**Comment by PHPGuus** [comment]
Further to the above, when I remove my permission for my browser to use my camera and microphone, eyeson.FeatureDetector.canUseEyeson() still returns true, without the browser asking me whether I should allow access to camera and microphone...

Can you detail what canUseEyeson() actually verifies, as the documentation on the FeatureDetector is rather thin.

Thank you!

**Comment by unused** [comment]
The `canUseEyeson` tests the browser client if it does fulfill the minimal requirements so you can handle user agents that are very outdated. Note that we do not check for specific browsers but try to figure out if basic JavaScript APIs and features are present, so we can support as many browser clients as possible. The device access permissions are not tested for the requirements check.

Unfortunately I don't know what you mean by "audio and video feed", can you please provide further details?

**Comment by PHPGuus** [comment]
Further to the above, eyeson.FeatureDetector.hasMobileApp() does not seem to be a function in the latest release of the eyeson JS package...

By "audio and video feed" I mean to indicate that no participant could see Adam or hear Adam.

Thank you!

**Comment by unused** [comment]
Thank you for the heads up, I've updated the section in documentation.

Did you ensure your participant did allow camera and microphone access in your user interface? Did your participants receive any errors (e.g. console logs)? Did you ensure your participants does use a recent browser client?

**Comment by PHPGuus** [comment]
Hi Christoph,

I did not capture any of that information / possibilities. I am in the
process of doing that right now, so that I capture navigator.userAgent and
it's capabilities and show the user his / her own media stream before I let
them join the conference... Hopefully that settles everything and we'd have
more debug information to go on in the future!

Best regards,
Guus

**Comment by unused** [comment]
Let us know if we can help - you can also try to check if the browser client is working using the default web GUI to have some reference as it is using the same base library. Best wishes!
