### ISSUE TITLE
customize each participant's video cell

### ISSUE THREAD

**Issue by VictorTao1998** [eyeson-team/react-web-gui-example#14]
Hi dev team,
Can I customize each participant's video cell? such as rearrange the order of video cell at the 9-video-window layout mode?

**Comment by unused** [comment]
You can use several different video layouts and assign users to specific positions. Please find details in the [layout section of the API documentation](https://eyeson-team.github.io/api/api-reference/#layout).

**Comment by VictorTao1998** [comment]
Is it possible to have a layout which  has more than 9 people?

**Comment by VictorTao1998** [comment]
and the api seems to only support rearrange layout at maximum of 4 people.

**Comment by unused** [comment]
Yes, we currently do not provide more than 9 people and more then 4 people are handled by the auto-layout.
