### ISSUE TITLE
Screen sharing issue

### ISSUE THREAD

**Issue by PHPGuus** [eyeson-team/react-web-gui-example#16]
Hi there,

using the React code, I copied the screen sharing code to send a start_screen_share into eyeson while I was using FireFox on Fedora 32 and the only person in the conference room. My cam and audio were switched on as well prior to sending the start_screen_share message.

Firefox asked me whether I wanted to allow screen sharing and which window I wanted to share. After making selection and allowing Firefox to share my screen, my system became unresponsive as far as I could tell, even though the webcam image was still showing and playing in the conference room.

Questions:
1) Have you ever seen this sort of behaviour?
2) Would it be better if the cam was switched off before switching on screen sharing?
3) Does the eyeson JS Library automatically switch off the cam before starting to capture the screen?

Thank you and best regards,
Guus

**Comment by PHPGuus** [comment]
Hi there,

so, switching off the cam is better!

One issue remains, though: after I stop_presenting and toggle my cam back on, it keeps showing the screen capture stream. Even when I then switch off my cam and back on, the <video> element is still displaying the shared screen. How can I make it so, that the video player's stream is actually changed back to the camera?

Thank you and best regards,
Guus

**Comment by unused** [comment]
Hi! Great choice for OS, we have some developers using Fedora as well but did not experience any freeze so far :( However some browser clients have issues with Wayland so you might want to give it a try to use classic window display server. Regarding the stream switch, did you check the [react web gui example](https://github.com/eyeson-team/react-web-gui-example) as it demonstrates a screen-sharing feature as well?

**Comment by PHPGuus** [comment]
Hi!

Yes, I more or less copied that example... I just now see that I missed the event "presentation_ended" that switches the stream back to cam, presumably! I'll implement that tonight, and will let you know whether that resolved my issue!

Regards,
Guus

**Comment by PHPGuus** [comment]
Hi, that works like a charm now ;-) Thank you!

**Comment by opusonline** [comment]
Thanks for using eyeson and sharing your feedback!
I just wanted to add some quick answers to your initial questions.

> 2. Would it be better if the cam was switched off before switching on screen sharing?
> 3. Does the eyeson JS Library automatically switch off the cam before starting to capture the screen?

eyeson JS library does indeed switch off the cam automatically before starting to capture the screen - but only when screen share request is successful.

I'm glad you could solve the issue already by yourself!

Happy coding!
