### ISSUE TITLE
Youtube streaming and recording functionality

### ISSUE THREAD

**Issue by alamgira** [eyeson-team/react-web-gui-example#17]
Hello,
Is there any way to enable streaming and recording functionality with javascript. I am trying to do 3 thing and everything needs to be happening from our site and not app.eyeson.com. 

1) Stream live from the room on your own
2) Stream live from the room with a participant
3) Have the functionality to record the video

**Comment by unused** [comment]
Hi there, you can use the access-key of the participant to control [broadcasts](https://eyeson-team.github.io/api/api-reference/#broadcast) and [recordings](https://eyeson-team.github.io/api/api-reference/#recording) from client-side using the API. To broadcast, the user has to know the [RTMP URL and stream key](https://help.eyeson.com/live-streaming-with-eyeson) from the platform. Please choose `generic` as platform type (even for youtube and facebook).
The recording feature also provides shorthands in the [JavaScript package](https://eyeson-team.github.io/js-docs/events/#recording) but you can use the API as well - that's what the shorthand does as well.
Please do not hesitate to open another issue or leave a comment if you have any further questions!
