### ISSUE TITLE
Eyeson room opens EyesOn app but not the meeting

### ISSUE THREAD

**Issue by codingyourlife** [eyeson-team/react-web-gui-example#18]
Steps to reproduce:

1. Install the EyesOn app
2. Open e.g. https://app.eyeson.team/?nrORMxCYEJ4mrRPJdYxRBY5U on mobile

-> The eyeson app opens but on the main page and it does not open the room.

It would be an improvement if the app does not open at all. Ideally of course it should open the correct room also in the app.

Please fix :)

**Comment by unused** [comment]
Thank you for the feedback, this issue however is not related to the eyeson API services. I'll forward your message to our mobile development team. If you have any further question please have a look at our [help center](https://help.eyeson.com/), there is also a method to contact the eyeson support.

**Comment by codingyourlife** [comment]
Ok cross-reported it here now: https://github.com/eyeson-team/api/issues/93

(otherwise I don't know how we get notified that it is fixed)

**Comment by unused** [comment]
> otherwise I don't know how we get notified that it is fixed

You can find details of any mobile application update in the corresponding release notes.
