### ISSUE TITLE
vuejs

### ISSUE THREAD

**Issue by juliengriffonwinwin** [eyeson-team/react-web-gui-example#23]
Hi,
do you have an equivalent project with VueJS ?
Cordialy

**Comment by opusonline** [comment]
Hi,
unfortunately we have currently no VueJS project to share.
Please do not hesitate to open another issue or leave a comment if you have any further questions!
Best regards, Stefan

**Comment by unused** [comment]
I'd love to have a Vue.js example project as well but the JavaScript package is pretty simple to use and abstracts many things away. Therefore it can be used with a few lines of code in vanilla JS [as demonstrated in the documentation](https://eyeson-team.github.io/js-docs/). What are you looking for in particular @juliengriffonwinwin ?

**Comment by juliengriffonwinwin** [comment]
Hi,

As explained in a previous ticket eyeson no longer works in iframe integration mode (in chrome 88 impossible to activate the camera, idem in microsoft edge who use the same navigator engine)
Is it strange that you are unable to reproduce this bug? It's not a eyeson bug we know (We have the same with other visio tools)

So we will no more use iframe and develop our interface with your JS package.

Thanks to your example, we succeeded in making a first functional version with the nuxt / vuejs framework.

Your example does not have the chat icons, list of ico participants etc. Why ? we have to code it ourselves?

Thanks

**Comment by unused** [comment]
The example is kept very simple but we're happy to provide snippets or point to documentation if you need any help. If you want to build a participants list you can do so by observing the `add_user` and `remove_user` events, see the [documentation](https://eyeson-team.github.io/js-docs/events/#joining-and-leaving-users) for details on the event structure. Very similar you can observer `chat` event for incoming messages and also `send_chat` messages, using `eyeson.send`, find further [details in the documentation](https://eyeson-team.github.io/js-docs/overview/).

**Comment by unused** [comment]
It also helps checking the eyeson UI e.g. checking the network requests. Please do not hesitate to contact if you have any questions!

**Comment by Matthias-dmt** [comment]
Hi, thanks for your answer. Can i separate the video fluxs to make several source of video ?

**Comment by unused** [comment]
I'm not sure what you are trying to achieve. Can you give a short description of your goal/requirement?
