### ISSUE TITLE
Video meeting not showing - 403 forbidden is coming

### ISSUE THREAD

**Issue by kvvaradha** [eyeson-team/react-web-gui-example#24]
Hello eyeson team, 
It was worked fine yesterday. and from today morning it shows 403 forbidden error. 

can i get a solution for this problem. ?

**Comment by unused** [comment]
Hi, can you please provide some details where this error comes up?

**Comment by kvvaradha** [comment]
hi thank you for the prompt response. 
hope this help you to understand 

Error during service worker registration: DOMException: Failed to register a ServiceWorker for scope ('https://example.in/') with script ('https://example.in/service-worker.js'): The script has an unsupported MIME type ('text/html').

**Comment by unused** [comment]
This seems not to be related with eyeson or the react web ui example in any way. If exampl.in is your local environment setup you'll likely have to check what's missing there.

**Comment by kvvaradha** [comment]
i am sorry to re open this issue again. The same files worked last night. and from today morning it failed to work. And i tested locally and also in server. both creates the same error. and i brought the error from server. From local i got warning like forbidden 403.  But now both places it takes up to use i didnt understand the reason.

**Comment by unused** [comment]
Can you please give a brief description of what you are trying to do, what files you are talking of?

**Comment by kvvaradha** [comment]
This is the error occurs, 

" DOMException: Failed to register a ServiceWorker for scope ('https://example.in/') with script ('https://example.in/service-worker.js'): The script has an unsupported MIME type ('text/html'). " 


sometimes, it works and sometimes it didnt work, even the same file, it didnt work, i tried both locally and also in server. it works sometime and it issues error sometime. 

This is happens, and from console, i see more codes are coming, and dont know what to your explain you more with this issue.

**Comment by unused** [comment]
Sorry to hear you still end up in this error but I cannot see any problem with the example and can only help if you can provide some details so that we can reproduce the issue.
As it seems to be related with service worker please try to test in incognito browser windows to avoid issues caused conflicting session data. Best wishes!
