### ISSUE TITLE
How to handle denied permissions? Can I re-trigger ask for permissions?

### ISSUE THREAD

**Issue by codingyourlife** [eyeson-team/react-web-gui-example#27]
Hi! Is there a way to manually (re-)trigger the device permissions? We have problems on mobile where it only works because of our fallback solution where the page reloads after 30 seconds if something failed. I am mentioning this because it is not just about manually declining permissions as described bellow. But troubleshooting on mobile isn't that easy I think.

I now have an easy way to reproduce it on Desktop. Opera has an option to deny the permissions and reload the page.
<img width="396" alt="Screenshot 2021-03-15 at 20 09 55" src="https://user-images.githubusercontent.com/10122382/111208451-072a4c80-85cb-11eb-9ea5-72a6b7047975.png">

This seems to be the error that occurs:
<img width="556" alt="Screenshot 2021-03-15 at 20 09 31" src="https://user-images.githubusercontent.com/10122382/111208479-10b3b480-85cb-11eb-8c37-cfe43f1faa24.png">

I then only see a Loading indicator. I guess it's fine that there is an error but ideally it would automatically ask again for the permissions, right?

Can we somehow handle this error on our side or is this something to fix in the SDK?

**Comment by unused** [comment]
Using Opera 74 on Win10 I cannot reproduce this behavior on the default web UI, the react example for sure is build with less error handling. On a custom UI you can easily test for permissions as well and show a proper message.

![Screenshot from 2021-03-16 07-21-08](https://user-images.githubusercontent.com/59397/111266195-78e5b300-862a-11eb-873a-b80534c5fa9a.png)

Let me know if you need any further help with this.
