### ISSUE TITLE
Can't use this repo on localhost

### ISSUE THREAD

**Issue by Dhananjay03121997** [eyeson-team/react-web-gui-example#29]
i tried to implement this on localhost bt facing some issue with the  guest link.

**Comment by unused** [comment]
How can we help? Can you give us a short description on your steps done and problem facing? Tia!

**Comment by Dhananjay03121997** [comment]
I was trying this repo on localhost but after running I get that started on localhost but how can I get a guest link?
and also I want to change the DNS address.

**Comment by unused** [comment]
There might be some misunderstanding regarding the eyeson API so it might be best to check the introduction resources like the [beginners guide](https://www.youtube.com/watch?v=VMPhqAprv94) or [developer overview](https://accounts.eyeson.team/developer).

To run this project on your local machine please setup a JavaScript environment including [yarn](https://classic.yarnpkg.com/en/docs/install/#debian-stable) and follow the instructions from the [README](https://github.com/eyeson-team/react-web-gui-example#eyeson-web-gui-build-with-react).

Please do not hesitate to leave a comment if you need any further help!
