### ISSUE TITLE
can we change the domain name for from eyeson to something else and also change the UI 

### ISSUE THREAD

**Issue by Dhananjay03121997** [eyeson-team/react-web-gui-example#30]

**Comment by unused** [comment]
The default eyeson web UI is built to provide you an easy way to start. If you want to make customizations it is very easy to get started with your own UI. We also provide [helpers](https://eyeson-team.github.io/js-docs/overview/) to do so. For sure you can use any domain when hosting you own eyeson web client.

**Comment by Dhananjay03121997** [comment]
yeah, that would be great if we get help from your side in that process. just can you tell me how can we reach you for that?

**Comment by unused** [comment]
Hopefully you find any details you need in the [developer examples and documentations](https://accounts.eyeson.team/developer). If you run into a specific problem do not hesitate to create an issue at one of the GitHub repositories.
