### ISSUE TITLE
changing domain from eyeson to https://real-estate-booking-portal.herokuapp.com

### ISSUE THREAD

**Issue by Dhananjay03121997** [eyeson-team/react-web-gui-example#31]
we are using eyeson on the Heroku app so can you tell me how can we change the domain name?

**Comment by unused** [comment]
If you want to run this example on your heroku app, simply adapt the configuration in the [package.json](https://github.com/eyeson-team/react-web-gui-example/blob/main/package.json#L2). This example is built reactjs so you might find details in the [reactjs documentation](https://reactjs.org/docs/getting-started.html).
