### ISSUE TITLE
Domain change

### ISSUE THREAD

**Issue by Dhananjay03121997** [eyeson-team/react-web-gui-example#32]
Currently, i want to change the domain link only not want to change the UI at current so please help me with the domain change and tell me how can I change the domain name for eyeson video call.

**Comment by unused** [comment]
As mentioned in #30 you can use the default web UI which is hosted at eyeson only. For custom domains you have to create a custom web UI.

You might also use an iframe to include the default web UI, but please note that [a proper configuration](https://github.com/eyeson-team/api/issues/18#issuecomment-509104239) is needed and we don't provide support on this method. Also future changes in browser clients or at the default web UI can lead to issues using iframes.
