### ISSUE TITLE
Handle cam/mic permission denied. How to retrigger cam/mic access.

### ISSUE THREAD

**Issue by codingyourlife** [eyeson-team/react-web-gui-example#35]
So I found out that via `event.type === "error"` and `event.name === "permission"` you can find out if there is a problem with blocked cam/mic permission. But now I want a button to ask the user again for permission. How can I do that?

**Comment by codingyourlife** [comment]
Aha seems you can only ask for permission once [https://stackoverflow.com/a/40108869/828184](https://stackoverflow.com/a/40108869/828184)

**Comment by opusonline** [comment]
Hi @codingyourlife,

great that you've already found an answer. As you said, after we notice the permission error, we can only show a notification to the user that access to camera and microphone is blocked and we ask for giving access.

Happy coding 😄
