### ISSUE TITLE
Error: Cannot read property 'received' of undefined in eyeson.js line 51

### ISSUE THREAD

**Issue by codingyourlife** [eyeson-team/react-web-gui-example#37]
We just received this error (see images). I hope this is enough information you can contact me for the full sentry JSON report or if you need further details.

I'd say from the error message that this is a bug in the SDK but please tell me if I'm mistaken.

<img width="508" alt="Screenshot 2021-08-30 at 15 39 45" src="https://user-images.githubusercontent.com/10122382/131348611-72d88035-31cd-46b3-a33c-2ae69172d43c.png">

<img width="862" alt="Screenshot 2021-08-30 at 15 39 17" src="https://user-images.githubusercontent.com/10122382/131348599-a0ffb3b5-1c75-452f-8a13-bfd18ba7a4df.png">

Cheers!

**Comment by unused** [comment]
Thanks for the details, we'll check this asap.

**Comment by unused** [comment]
An update that should handle the problem has been released.
