### ISSUE TITLE
Vanilla JS integration

### ISSUE THREAD

**Issue by rohithcirakas** [eyeson-team/react-web-gui-example#39]
Hi Team, we are trying to integrate Eyeson video chat with our application(Angular JS+html). Is there any documentation/hello world demo for the Vanilla JS integration ?.What we are trying to achieve is, integrating your's default UI into our application.

**Comment by unused** [comment]
Hi there, sounds great! Please have a look at the [documentation](https://eyeson-team.github.io/js-docs/) of the [eyeson JavaScript package](https://www.npmjs.com/package/eyeson). There is also a [blog post](https://techblog.eyeson.team/posts/basic-web-gui/) in our development blog that covers some common actions.

We do not share the code of the default web UI but are happy to explain any details on how we implemented certain features there. For sure we can also come up with examples if needed.

Do not hesitate to leave a comment or open an issue at one of the repositories if you have any technical questions, get stuck at some point or need any other kind of hint!
