### ISSUE TITLE
Advanced GUI available too?

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [eyeson-team/react-web-gui-example#4]
Hi guys,

I just wanted to ask if the sourcecode of your default video client implementation is also available?
Recreating the whole interface (gifs, icons, presentations,..) takes a lot of time, so I thought you could make it available too - which helps to customize it easier than to rewrite it from scratch by myself?

Thanks!

**Comment by unused** [comment]
Ahoi! That's a great question, our decision was to provide you with as many helpers as needed to built a custom GUI with ease but not publish the one provided by eyeson. There are many reasons to do so: it is huge and quite complex, has many features we connect with other services, uses external dependencies - like a material UI package - you won't need, and we change it on a daily basis. If you have any troubles while building your own custom interface, please feel free to open an issue for the specific parts, we're happy to help.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Ok, this is a bit unfortunate for us.. Since it takes a pretty big amount of work to implement all this stuff (presentations, chat,..) I'm not sure if this is a practical solution for us. If there is the source code available, it would be at least possible to customize it to our needs somehow.. Without it, we would have to write everything from scratch, which we probably won't do for smaller or medium projects which we have right now.

Do you think there is maybe a solution to get at least the presentation tools working somehow, without writing it from scratch?

**Comment by unused** [comment]
Sorry to hear, however I can assure you building the corresponding features is easier and way quicker done than adapting our corporate GUI. All tools are already at hand with the eyeson package. For smaller or medium projects I guess it might be fitting to use the eyeson web GUI and adapt the configuration it to your needs. For any custom implementation, as mentioned, if you come up with any issue or specific part you are stuggling, we are happy to help (share knowledge, provide an example, etc). Best wishes!

**Comment by h0jeZvgoxFepBQ2C** [comment]
Ok, do you have an example on how the presentation and screenshare-stuff can be implemented?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Would be great if you have a tip for us..

**Comment by unused** [comment]
I've [updated the react example](https://github.com/eyeson-team/react-web-gui-example/commit/849de7cb4289107a2bb3b77261852b71c23136f1) with a simple example similar to how it is used in the eyeson GUI. Another approach is to simply use the [web screen capture API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture) and replace the stream. The example provided however also switches layout to a single mode for the one presenting.
