### ISSUE TITLE
Babel polyfill is dead. Long live core-js!

### ISSUE THREAD

**Issue by codingyourlife** [eyeson-team/react-web-gui-example#42]
Hi,
we have this message on compile due to eyeson package
<img width="1036" alt="Screenshot 2021-12-19 at 16 17 55" src="https://user-images.githubusercontent.com/10122382/146681307-14a76d47-6c2f-4f01-a278-05759f2188af.png">

@babel/polyfill package is used by eyeson npm package...

When you open @babel/polyfill on npm website it has big warnings all over the place that it is outdated:
[https://www.npmjs.com/package/@babel/polyfill](https://www.npmjs.com/package/@babel/polyfill)
<img width="1407" alt="Screenshot 2021-12-19 at 16 49 15" src="https://user-images.githubusercontent.com/10122382/146681359-7089a48d-dffb-44ef-aaa9-3496e27055a2.png">

Here a blog I've found which seems to explain how to upgrade to corejs3:
[https://alexbogovich.com/blog/core-js/](https://alexbogovich.com/blog/core-js/)

So the new package to use seems to be [https://www.npmjs.com/package/@babel/runtime-corejs3](https://www.npmjs.com/package/@babel/runtime-corejs3)

I didn't dig very deep but "100x" sounds significant and "even if nothing is polyfilled" doesn't sound any better. And it's really warnings all over the place about this. So would be great if you could upgrade soon 🥇 

Regards,
Johannes

**Comment by opusonline** [comment]
Hello Johannes,
thanks for your feedback!
I will let you know as soon as the update is published.
Best regards,
Stefan

**Comment by opusonline** [comment]
Hello Johannes,
I'm happy to inform you that a new version of the eyeson package is available.
https://www.npmjs.com/package/eyeson/v/1.7.0
Best regards,
Stefan
