### ISSUE TITLE
Display video local

### ISSUE THREAD

**Issue by pesuyn** [eyeson-team/react-web-gui-example#43]
Hi,
In Find the build project at eyeson-team.github.io/react-web-gui-example, I can see all users' videos but in my locallhost only show the user's video, like the picture below:
In my localhost:
![image](https://user-images.githubusercontent.com/69211021/146879223-02e143f3-247c-4103-9f6b-5abf1fc99afe.png)
Find the build project at eyeson-team.github.io/react-web-gui-example:
![image](https://user-images.githubusercontent.com/69211021/146879456-05712c2e-ba8e-4ac9-8b73-38b2df02f7fe.png)

I would like to ask why is it so different and can you provide the source code for me to develop?
Regards,
Thuy

**Comment by unused** [comment]
The video client is pretty independent so we do provide a pre-build one for you that includes many state of the art features like file presentations, screenshare, and others. This is the client you are using on your phone. The [example web client](https://github.com/eyeson-team/react-web-gui-example) you run on your local host is a minimal setup for a custom user interface build with [React](https://reactjs.org/). It does not show the own live video in SFU mode (two participants), so you can either [change](https://eyeson-team.github.io/api/api-reference/#eyeson-room) the `sfu_mode` of the video meeting to disabled or join with a third participant to see yourself in the [single stream](https://help.eyeson.com/what-is-single-stream-technology).

If you want to create your own video client we recommend to have a look on the [JavaScript package](https://eyeson-team.github.io/js-docs/) that includes many helpers to get you started. Please give the [help center](https://help.eyeson.com/api-coding-examples) a try if you have further questions. In case you are stuck do not hesitate to open an issue at any of our GitHub repositories, we are happy to help!
