### ISSUE TITLE
ComApiError: 500 - Cannot see or hear the other person but he can. Reproduced right now myself!

### ISSUE THREAD

**Issue by codingyourlife** [eyeson-team/react-web-gui-example#45]
So upfront we are tracking down this bug for quite a while and I have it reproduced myself right now.

It's quite serious because the joining person does hear and see me but I do not hear or see the other person so the first person in the room likely does not realize that the meeting started! Meanwhile we have a person presence indication and it even shows that someone joined see here:

It happened around 19:08 on 10. January for me debugging the problem on Smartphone and MacBook but also happened today to a real and important customer.

On my macbook where I was the 1st person in the room:
<img width="570" alt="image" src="https://user-images.githubusercontent.com/10122382/148826474-84cf2b04-3fb7-4dbe-b580-24d0eb643f9d.png">

On my iPhone 11:
![image](https://user-images.githubusercontent.com/10122382/148826583-7fb8bdbf-8e7a-4824-8b76-6735220d5da5.png)

-> If you contact me ASAP I maybe still have it open.

So this happened - Error 500 in eyeson.js:51 :
<img width="1440" alt="Screenshot 2022-01-10 at 19 45 11" src="https://user-images.githubusercontent.com/10122382/148823899-30abeec6-8104-4222-b2f1-4f90b9c1551e.png">

In prettified eyeson.js the code part looks like this:
<img width="524" alt="Screenshot 2022-01-10 at 20 05 17" src="https://user-images.githubusercontent.com/10122382/148824206-65abc9fc-f03b-42dc-8c34-08f33e53f17a.png">

Afterwards a handling of the error happens in the eyeson code:
![image](https://user-images.githubusercontent.com/10122382/148824965-3d530071-0cb7-411e-aca0-21edd871df34.png)

This handling can be one of the following:
<img width="605" alt="image" src="https://user-images.githubusercontent.com/10122382/148825307-839a8c74-4b0c-499d-a72d-936ccd71ec8e.png">
Interestingly I cannot see "session" here.

There is an error in the console that says this:
![image](https://user-images.githubusercontent.com/10122382/148825731-715ef36e-61cc-4329-82a9-28be3771b45e.png)
Error: A session is already set. If you are trying to start a new session you have to end the current one first.

So it was handled as session already in use for some reason. In the code it is this:
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/10122382/148826051-bafe3200-8a2f-4732-896c-da7bec834022.png">

The corresponding code in eyeson master (maybe outdated version) is this:
<img width="614" alt="image" src="https://user-images.githubusercontent.com/10122382/148824414-25d77706-ff58-42d0-8f60-a3a7f15b3cb9.png">

So how can I listen to this error so in case it happens I can at least notify the user and ask him to refresh the browser or repeat on the backend the API call or whatever. The problem here is that it is so hard to reproduce.

Any help much appreciated and as I said if you contact me ASAP I might still have it set up.

**Comment by unused** [comment]
Thank you for the details, we're already looking into the issue and leave a reply as soon as we have any updates.

**Comment by codingyourlife** [comment]
Great thanks!

I will leave videoroom open for another 1-2 hours. I've sent my phone number to support email in case you need to extract more info this might help.

Additional info: This morning I tried if it's still an issue but I assume my smartphone killed the connection at some point. Safari auto-reloaded the page and it was working then. The client allegedly tried reloading but I can only describe my experience.

**Comment by unused** [comment]
We could reproduce this issue: In case two participants initially join the meeting at a very close time span, it does break the connection initialization in the session create process. Our test team is currently doing final checks, I'll leave a comment when the fix has been deployed to production. There is no update required from your side.

**Comment by unused** [comment]
All production services have been updated.
