### ISSUE TITLE
Query 

### ISSUE THREAD

**Issue by MridulTanwar** [eyeson-team/react-web-gui-example#5]
I was going through react-web-gui-example module in your git hub repository.  I am able to generate room using api call and using the generated access key I am able to join the meeting room in react-web-gui example.
However in our usecase we need to open similar webpage for a guest user as well. For the same , I have few queries queries which are mentioned below.
 Is there any api available to join the room with guest user in react module.
Is there any documention for the eyeson's react library and its dependencies.

**Comment by unused** [comment]
eyeson does not provide any user or role management so you can handle this in your application in any way you need to. In case you want to start a video conversation simply ensure the user can start or join a meeting, then do so on joining a room at eyeson. If you want to have several people to join the same meeting, provide a unique identifier for those users. This is the common way how to handle participants.

Additionally you can use the [guest token](https://eyeson-team.github.io/api/api-reference/#user-and-guest-user) provided to invite users quickly within an active meeting.

You can use the eyeson hosted web interface to redirect your users or build your own GUI. The react example is a very basic one we setup to demonstrate how easy it is to build meeting controls with modern tools. So you can use any of such frameworks like svelte, react, vue, angular, etc. or none at all, however we recommend to use the [eyeson JavaScript package](https://eyeson-team.github.io/js-docs/) as it ships with a lot of helpers.

If you have any further questions do not hesitate to leave a comment :)
