### ISSUE TITLE
React - Virtual background plugin - Video room - Errors in files

### ISSUE THREAD

**Issue by peterminea** [eyeson-team/react-web-gui-example#54]
Hello, EyesOn team!

My name is Peter Minea and I work on the same project (HalloSophia) as Johannes Mayer (codingyourlife), as a front-end React developer. 
I am also going to report an issue concerning the React integration of the Virtual Background feature. This branch seems to be appropriate for reporting the problem.

Thanks for helping and kind regards!

Description:

When integrating the Virtual background / Blurry background plugin into the video room with React front-end, there are some errors (including syntax). No visual effect is then applied to the video.
Affected files: **tflite-simd.js** and **VirtualBackgroundMixer.js**.

Screenshots attached:
![VIDEO_ROOM](https://user-images.githubusercontent.com/59822528/166015503-e523f5c4-6a15-4a16-b143-8cb15b0ee2b5.png)
![VIDEO_ROOM2](https://user-images.githubusercontent.com/59822528/166040101-99fe93fb-0a6c-41f1-927d-3fbca046ee92.png)

**Comment by unused** [comment]
Hi Peter, how are you doing? Did you follow the [instructions from the vbg techblog post](https://techblog.eyeson.team/posts/virtual-background/) to setup your feature? Unfortunately this error might be caused by your implementation, rather than the eyeson library. Please double check your sources, in case you still struggle with an issue feel free to leave a comment, best including some details on how your code differs from the blog post and error messages in text format rather than screenshots. Best wishes!

**Comment by peterminea** [comment]
Hello Unused!

Although the **vendor** folder in the "**public**" folder of our Frontend exists as in the blog post, the errors still persist. 

The **tflite-simd.js** file is taken from /vendor/tflite, but its <!DOCTYPE html> tag at the start is treated as a syntax error (Uncaught SyntaxError: Unexpected token '<' (at tflite-simd.js:1:1)).

The other file **VirtualBackgroundMixer.js** is used directly from the eyesOn source files (eyeson/src/VirtualBackgroundMixer.js), its line 12 has

window.exports = window.exports || {};
and at the line 68 we have
const initiateTFLite = async () => {

that is marked as a red line in the browser. The error message would claim that 
window.exports[(intermediate value)(intermediate value)(intermediate value)] is not a function.

The errors appear when I call this code:

eyesonClient.send({ 
			type: 'start_stream', 
			audio: true,
			video: true, 
			virtualBackground: !state.virtualBackground
		 });

"state" is an object that we built, and the field virtualBackground can be true or false there. When wanting to set **virtualBackground** to true, the errors happen.

The vendor folder in our "public" parent folder has the structure as in the blog post, with **models:** as a subfolder:

vendor/tflite/
|-- tflite.js
|-- tflite.wasm
|-- tflite-simd.js
|-- tflite-simd.wasm
|-- models/
|   |-- selfie_segmentation_landscape.tflite

The text of the errors in the browser F12 is:

tflite-simd.js:1 Uncaught SyntaxError: Unexpected token '<' (at tflite-simd.js:1:1)
VirtualBackgroundMixer.js:68 Uncaught (in promise) TypeError: window.exports[(intermediate value)(intermediate value)(intermediate value)] is not a function
    at VirtualBackgroundMixer.js:68:1
    at l (runtime.js:63:1)
    at Generator._invoke (runtime.js:294:1)
    at Generator.next (runtime.js:119:1)
    at et (asyncToGenerator.js:3:1)
    at a (asyncToGenerator.js:25:1)

I also need to place two more screenshots with the red-marked error lines in the 2 files (line 1 in tflite-simd and line 68 on VirtualBackgroundMixer), as they are given in the browser console:

![image](https://user-images.githubusercontent.com/59822528/166267437-b72835bf-fddc-45ef-9af5-28b185524f54.png)
![image](https://user-images.githubusercontent.com/59822528/166267588-dbaa006d-38c6-4fe2-b803-68747a623321.png)

**Comment by unused** [comment]
Thank you for the detailed explanation! The content of the `tflite-simd.js` JavaScript file is wrong, I'd guess this is your (local webservers) 404 not found HTML source shown there. Please ensure the file is imported properly. The path of the second file you took a screenshot of looks a bit weired, but at least the source code loaded looks ok.
