### ISSUE TITLE
Is react-web-gui-example using latest eyeson 1.8.0 version?

### ISSUE THREAD

**Issue by codingyourlife** [eyeson-team/react-web-gui-example#56]
Is your example under [https://eyeson-team.github.io/react-web-gui-example/](https://eyeson-team.github.io/react-web-gui-example/) using the latest version of the eyeson package?

I have something I cannot reproduce in your demo but also not with a lower version so I am wondering if you maybe forgot to upgrade your react-web-gui-example to 1.8.0.

**Comment by unused** [comment]
It is using [version 1.8.0](https://github.com/eyeson-team/react-web-gui-example/blob/main/package.json#L7).
