### ISSUE TITLE
Open self view video in react

### ISSUE THREAD

**Issue by MridulTanwar** [eyeson-team/react-web-gui-example#6]
We are looking to show self video in react module. For this we added a video tag in app.js and src the video from local stream. Code looks like below
// Tag for remote video
{this.state.stream && <Video src={this.state.stream} />}
// tag for self video
                        {this.state.stream && <Video src={this.state.local}/>}

However ever we are self audio duplication(echo) if we source self video like above.
Can you please suggest the correct opening self view video without audio

**Comment by unused** [comment]
If you just want to mute the [video element use attribute muted](https://developer.mozilla.org/de/docs/Web/HTML/Element/video).
