### ISSUE TITLE
Webhook - retrieve screenshot data

### ISSUE THREAD

**Issue by dineshanchetty** [eyeson-team/react-web-gui-example#61]
hi there, 

I have set up the webhook successfully for recording_update, however, i don't seem to get any data for the screenshots taken during the video call.

`{
    "body": {
        "timestamp": 1661160472,
        "type": "recording_update",
        "recording": {
            "id": "63034c102e5c55000f190d84",
            "created_at": 1661160465,
            "duration": 6,
            "links": {
                "self": "https://api.eyeson.team/recordings/63034c102e5c55000f190d84",
                "download": "https://s3.eyeson.com/meetings/63034bee0e177a000ff22e3e/63034c102e5c55000f190d84?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AH07FBAZO9IYS38J6742%2F20220822%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220822T092752Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=e1d78d1d6aa32ad9a9e7039eb17f519776a4395e58bc546527ca78c9eb99a933"
            },
            "user": {
                "id": "63034bfd9062310010e32336",
                "name": "Admin User",
                "avatar": null,
                "guest": false,
                "joined_at": "2022-08-22T09:27:28.084Z"
            },
            "room": {
                "id": "63034bee0e177a000ff22e3d",
                "name": "dineshan chetty",
                "ready": true,
                "started_at": "2022-08-22T09:27:10.736Z",
                "shutdown": false,
                "sip": {
                    "uri": "conf_63034bee0e177a000ff22e3e@integrations.visocon.com",
                    "domain": "integrations.visocon.com",
                    "authorizationUser": "conf_63034bee0e177a000ff22e3e"
                },
                "guest_token": "q2TGKFg5P15jRf0QHfEJouD5"
            }
        }
    },
    "headers": {
        "host": "risksure.bubbleapps.io",
        "connection": "close",
        "accept-encoding": "gzip",
        "x-forwarded-for": "109.70.102.200,::ffff:172.71.146.45",
        "cf-ray": "73ea93372ce577f8-SEA",
        "content-length": "1062",
        "x-forwarded-proto": "https,https",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "accept": "*/*",
        "user-agent": "Ruby",
        "content-type": "application/json",
        "x-eyeson-signature": "9acd0ebe2a78f56106765f1c3f2c760859b30314546e39065a7e9979ac114625",
        "cf-connecting-ip": "109.70.102.200",
        "cf-ipcountry": "AT",
        "cdn-loop": "cloudflare",
        "x-forwarded-port": "443",
        "x-forwarded-host": "risksure.bubbleapps.io"
    }
}`

**Comment by unused** [comment]
You need to register the webhook for `snapshot_update` as well. Seems this one is missing in the documentation, thank you for the heads up, we'll update it soon.

**Comment by dineshanchetty** [comment]
Hi Christopher

Many thanks, however I noted that we not able to create multiple webooks? Problem- when I initialise the webhook I receive a packet of data for the snapshot and not the recording. Need to setup two different urls in the webhook

**Comment by unused** [comment]
Please register your webhook with all types comma-separated - `snapshot_update,recording_update` to receive all events.
