### ISSUE TITLE
Provide a blur button in the example, broken link, improvement suggestions

### ISSUE THREAD

**Issue by codingyourlife** [eyeson-team/react-web-gui-example#67]
The blur and custom background is really tricky (more than it has to be). At least the frontend part with the tensorflow model.

Your link to TFLite model in the blog entry is down: [https://docs.eyeson.com/blog/virtual-background/#meeting-usage](https://docs.eyeson.com/blog/virtual-background/#meeting-usage)

I THINK I found the correct model but then I ran into problems with eyeson forcing relative paths and our software ads /en lang prefix so the path is wrong then. I tried adding the vendor folder on public/en also but then it tries to find it in public/en/meet (not sure where meet is coming from) so it is really really not compatible with our solution. I managed to work around it by adding a "/" in front of the vendor paths in the eyeson package. In twilio it seems they export a path which I guess can be set from external. maybe a check if it is the same host or starting with a "/" in case you have security concerns.
<img width="496" alt="Screenshot 2023-11-12 at 07 43 21" src="https://github.com/eyeson-team/react-web-gui-example/assets/10122382/5db6cd31-3a14-4b66-b8dd-a2068cbbce4a">

I also noticed that VirtualBackgroundProcessor of twilio delivers the model and other needed files as part of the package which would be a bit easier to host then.

eventually I could find and load the model but _getOutputMemoryOffset() returns 0:
<img width="1440" alt="Screenshot 2023-11-12 at 02 04 43" src="https://github.com/eyeson-team/react-web-gui-example/assets/10122382/5a31b83c-1410-4052-8ded-e74710739932">

**Comment by opusonline** [comment]
Hello and thanks for your feedback!

I will have a closer look and get back back to you then.

Best regards

**Comment by opusonline** [comment]
Hello,

as promised I inform you that a new version of eyeson-js has been published. The current version is 1.8.9 and it supports a customizable script path for virtual background.
The blog article has been updated accordingly.

https://docs.eyeson.com/blog/virtual-background
https://docs.eyeson.com/docs/js/fundamentals/configuration

Please do not hesitate to leave a reply if you have any further questions.

Best regards
