### ISSUE TITLE
Make Video/Audio Quick Test accessible for react gui customers

### ISSUE THREAD

**Issue by codingyourlife** [eyeson-team/react-web-gui-example#68]
The Quick Test is nice ([https://app.eyeson.team/quicktest/](https://app.eyeson.team/quicktest/)): [https://help.eyeson.com/camera-problems](https://help.eyeson.com/camera-problems) but it would lead to eyeson eventually and not our videoroom in react. Can you also OpenSource it? Alternatively can you add a url parameter where to link with the final button press.
![image](https://github.com/eyeson-team/react-web-gui-example/assets/10122382/c3fe66c7-3043-431f-8ab9-aa7a821fe5a7)

In case you have security concerns maybe you can hold a list of whitelisted domains and later a virustotal check or something.

**Comment by opusonline** [comment]
Hello and thanks for your feedback!

Unfortunately, this tool is only meant for our SaaS product and not the API. Making it available as OpenSource would introduce new problems and make it even more complex to handle.

EyesonJS offers many functions that can be used to create your own checks, like [FeatureDetector](https://docs.eyeson.com/docs/js/utilities/feature/) and [DeviceManager](https://docs.eyeson.com/docs/js/utilities/devicemanager).

Please do not hesitate to leave a comment if you need any further help!

Best regards
